[build]
  command = "npm run build && cp -r docs dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Add headers for better Opera compatibility
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy for Opera compatibility
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.dicebear.com https://nominatim.openstreetmap.org https://photon.komoot.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://vdfqhhfirorqdjldmyzc.supabase.co wss://vdfqhhfirorqdjldmyzc.supabase.co https://nominatim.openstreetmap.org https://photon.komoot.io https://api.dicebear.com https://api.openweathermap.org; worker-src 'self' blob:; child-src 'self' blob:; frame-src 'self'; media-src 'self' blob: data:;"
    
    # Other security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache versioned assets (JS/CSS with hash) for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images and media for shorter time
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# No cache for HTML files to ensure updates are seen immediately
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# No cache for index.html and root paths
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 