-- Populate exercise library with comprehensive system exercises
-- All system exercises are public by default

INSERT INTO public.exercise_library (name, category, is_system_exercise, is_public, description) VALUES
-- A exercises
('10-5-5 (Drill)', 'drill', true, true, 'Track and field drill'),
('180 Degree Jumps (180s)', 'plyometric', true, true, 'Rotational jumping exercise'),
('3 Pt. Stance Acceleration R/L', 'drill', true, true, 'Three-point stance acceleration drill'),
('3 Pt. Stance', 'drill', true, true, 'Three-point starting stance'),
('4 Bounds into strides', 'plyometric', true, true, 'Bounding exercise transitioning to strides'),
('4 way cable (Cable 4-way hips)', 'strength', true, true, 'Hip strengthening with cable machine'),
('90/90 Hip Switches', 'flexibility', true, true, 'Hip mobility exercise'),
('A Skip w-Clap (Backward Alternating)', 'drill', true, true, 'A-skip variation with clapping'),
('A Skips / A-Switches', 'drill', true, true, 'Fundamental running drill'),
('Accelerations (General, e.g., 2 pt. Standing, 3 pt. Standing, Kneeling)', 'running', true, true, 'Various acceleration techniques'),
('Adductor Stretch', 'flexibility', true, true, 'Inner thigh stretching'),
('Alternate Dynamic Walkovers', 'flexibility', true, true, 'Dynamic leg swing exercise'),
('Alt Highland Leg Swings', 'warm_up', true, true, 'Alternating leg swing warm-up'),
('Ankle Bounce', 'warm_up', true, true, 'Ankle mobility exercise'),
('Ankle Rotation', 'warm_up', true, true, 'Ankle mobility and strengthening'),
('Ankling', 'drill', true, true, 'Foot and ankle running drill'),
('Arm Across Skips', 'drill', true, true, 'Skipping with arm movement'),
('Arm Circle Skips', 'drill', true, true, 'Skipping with arm circles'),
('Arm circles (backwards and forward)', 'warm_up', true, true, 'Shoulder warm-up exercise'),
('Around the world on tape', 'drill', true, true, 'Agility drill on line/tape'),

-- B exercises
('B Skips', 'drill', true, true, 'Running drill progression'),
('Back Extensions (Hypers)', 'strength', true, true, 'Lower back strengthening'),
('Back Pedal', 'drill', true, true, 'Backward running drill'),
('Back Plank Hip Arch', 'strength', true, true, 'Core strengthening exercise'),
('Back Plank Leg Lifts', 'strength', true, true, 'Core and glute strengthening'),
('Back rolls', 'flexibility', true, true, 'Spinal mobility exercise'),
('Back Squats', 'strength', true, true, 'Compound leg strengthening exercise'),
('Backward A Switches', 'drill', true, true, 'Reverse A-skip drill'),
('Backward Lunges', 'strength', true, true, 'Reverse lunge exercise'),
('Backward pogos', 'plyometric', true, true, 'Backward hopping exercise'),
('Backward Skips', 'drill', true, true, 'Backward skipping drill'),
('Backward Squat Walk', 'strength', true, true, 'Squat walking backward'),
('Band internal and external rotation', 'strength', true, true, 'Shoulder rotation with resistance band'),
('Banded squat Jumps', 'plyometric', true, true, 'Jump squats with resistance band'),
('Barbell Hang Clean', 'strength', true, true, 'Olympic lifting movement'),
('Barbell Single Leg Clean', 'strength', true, true, 'Single leg Olympic lift variation'),
('Bear crawl pull throughs', 'strength', true, true, 'Full body crawling exercise'),
('Bench Press', 'strength', true, true, 'Upper body pushing exercise'),
('Bentover Rows', 'strength', true, true, 'Back strengthening exercise'),
('Between the Legs forward (throw)', 'plyometric', true, true, 'Medicine ball throw'),
('Bicycle with Rollover', 'strength', true, true, 'Core exercise variation'),
('Bikes (core exercise)', 'strength', true, true, 'Abdominal exercise'),
('Bird dog', 'strength', true, true, 'Core stability exercise'),
('Bleachers (running)', 'running', true, true, 'Stadium stair running'),
('Block Thigh Parallel (part of Frontside Mechanics cue)', 'drill', true, true, 'Running form drill'),
('Body rotations', 'warm_up', true, true, 'Torso rotation warm-up'),
('Bounds for Distance', 'plyometric', true, true, 'Horizontal bounding'),
('Bounds for Height', 'plyometric', true, true, 'Vertical bounding'),
('Bounds', 'plyometric', true, true, 'General bounding exercise'),
('Box - Between Legs Forward', 'plyometric', true, true, 'Medicine ball throw variation'),
('Box - Overhead Back', 'plyometric', true, true, 'Overhead medicine ball throw'),
('Box Jumps', 'plyometric', true, true, 'Jumping onto elevated platform'),
('Bridges to Pike', 'strength', true, true, 'Hip bridge to pike movement'),
('Broad Jump (Standing Long Jump / SLJ)', 'plyometric', true, true, 'Horizontal jumping exercise'),
('Bulgarian split squat', 'strength', true, true, 'Single leg squat variation'),
('Bunny hops', 'plyometric', true, true, 'Double leg hopping'),
('Burpee Pull Up', 'strength', true, true, 'Compound burpee with pull-up'),
('Burpees', 'strength', true, true, 'Full body exercise'),
('Butt Kick Jumps', 'plyometric', true, true, 'Jumping butt kicks'),
('Butt Kicks', 'drill', true, true, 'Running drill'),
('Butterfly (stretch)', 'flexibility', true, true, 'Hip flexibility stretch'),

-- C exercises
('C Skips', 'drill', true, true, 'Advanced running drill'),
('Calf raises on slant board', 'strength', true, true, 'Calf strengthening on incline'),
('Calf raises with lax ball', 'strength', true, true, 'Calf raises with lacrosse ball'),
('Calf stretch in push up position', 'flexibility', true, true, 'Calf stretching variation'),
('Calf Stretch (Standing R/L)', 'flexibility', true, true, 'Standing calf stretch'),
('Chair drill (for LJ/TJ)', 'drill', true, true, 'Long jump/Triple jump drill'),
('Chess passes (Medicine Ball)', 'plyometric', true, true, 'Medicine ball passing drill'),
('Chest Hang (stretch)', 'flexibility', true, true, 'Chest stretching exercise'),
('Chest Over Thigh (part of Frontside Mechanics cue)', 'drill', true, true, 'Running form cue'),
('Chin ups', 'strength', true, true, 'Upper body pulling exercise'),
('Circle Drill (HJ - pushing off the curve)', 'drill', true, true, 'High jump technique drill'),
('Circuit Paired Run', 'running', true, true, 'Partnered running drill'),
('Clams / Clamshells', 'strength', true, true, 'Hip strengthening exercise'),
('Clean (floor, knee, thigh)', 'strength', true, true, 'Olympic lifting variations'),
('Clean & Jerk', 'strength', true, true, 'Olympic lifting movement'),
('Clean pulls', 'strength', true, true, 'Olympic lift pulling phase'),
('Closed Everted Toe Squats', 'strength', true, true, 'Squat variation with foot position'),
('Cocked Foot (part of Frontside Mechanics cue)', 'drill', true, true, 'Running form technique'),
('Combo Bounds', 'plyometric', true, true, 'Combination bounding exercise'),
('Continuous 3 steps pop-ups', 'plyometric', true, true, 'Continuous jumping drill'),
('Cool-Down Stretches (general category, specific ones listed)', 'cool_down', true, true, 'General cool-down stretching'),
('Core exercises (general)', 'strength', true, true, 'General abdominal strengthening'),
('Cossack Extensions', 'flexibility', true, true, 'Deep lateral lunge stretch'),
('Cossack squat', 'strength', true, true, 'Lateral squat movement'),
('Cracks with med-ball', 'plyometric', true, true, 'Medicine ball exercise'),
('Crossover hops', 'plyometric', true, true, 'Lateral hopping exercise'),
('Crossover Runs', 'drill', true, true, 'Lateral running drill'),
('Crossover Step-Ups', 'strength', true, true, 'Lateral step-up exercise'),
('Crunches', 'strength', true, true, 'Abdominal exercise'),
('Crunches w/ Twist', 'strength', true, true, 'Rotational abdominal exercise'),
('Curtsy lunge', 'strength', true, true, 'Reverse diagonal lunge'),
('Curve work (HJ drills)', 'drill', true, true, 'High jump curve running'),

-- D exercises
('DB Calf Raises', 'strength', true, true, 'Dumbbell calf raises'),
('DB RDL', 'strength', true, true, 'Dumbbell Romanian deadlift'),
('DB Seated Jumps', 'plyometric', true, true, 'Seated jump with dumbbells'),
('DB Step Ups (keep toe dorsiflex)', 'strength', true, true, 'Dumbbell step-ups'),
('Dead bug', 'strength', true, true, 'Core stability exercise'),
('Dead lift', 'strength', true, true, 'Compound pulling exercise'),
('Decline push up', 'strength', true, true, 'Elevated feet push-up'),
('Deep Body Squats', 'strength', true, true, 'Deep squat movement'),
('Deep Squat (stretch)', 'flexibility', true, true, 'Deep squat hold'),
('Depth Drops / Depth Jumps', 'plyometric', true, true, 'Drop jumping exercise'),
('Diagonal hops', 'plyometric', true, true, 'Multi-directional hopping'),
('Dips', 'strength', true, true, 'Upper body pushing exercise'),
('DL Lateral Hops', 'plyometric', true, true, 'Double leg lateral hops'),
('Donkey kicks', 'strength', true, true, 'Glute strengthening exercise'),
('Double A Switches', 'drill', true, true, 'Double A-skip drill'),
('Double Double TJ / Double Double TJ Drill', 'drill', true, true, 'Triple jump technique drill'),
('Double Knee Tucks', 'plyometric', true, true, 'Double knee jumping exercise'),
('Double Leg Backward', 'plyometric', true, true, 'Backward double leg hops'),
('Double Leg Bounds', 'plyometric', true, true, 'Double leg bounding'),
('Double Leg Forward', 'plyometric', true, true, 'Forward double leg hops'),
('Drop Jumps', 'plyometric', true, true, 'Drop and jump exercise'),
('Dumbbell Hang Clean', 'strength', true, true, 'Dumbbell Olympic lift'),
('Dumbbell Snatch', 'strength', true, true, 'Dumbbell Olympic lift'),
('Dynamic Flexibility (general category of exercises)', 'warm_up', true, true, 'Dynamic warm-up movements'),
('Dynamic Scissors', 'flexibility', true, true, 'Dynamic leg swinging'),

-- E-F exercises
('Eagles', 'flexibility', true, true, 'Stretching exercise'),
('Eccentric pistol squats', 'strength', true, true, 'Single leg squat negative'),
('Elbow to Knee Lunge', 'flexibility', true, true, 'Dynamic lunge stretch'),
('Eversion with band', 'strength', true, true, 'Ankle strengthening with band'),
('Fast A Switches Rotary (No Bounce / Two Bounces)', 'drill', true, true, 'Fast A-skip variations'),
('Fast Five A Switches Rotary (Two Bounces)', 'drill', true, true, 'Fast A-skip drill'),
('Fast leg', 'drill', true, true, 'Fast leg cycling drill'),
('Fast Leg Continuous R/L', 'drill', true, true, 'Continuous fast leg drill'),
('Fast Leg Rotary Cycle R/L Only', 'drill', true, true, 'Single leg fast cycling'),
('Fast Leg Rotary Double R/L Only', 'drill', true, true, 'Double leg fast cycling'),
('Figure 4 bridge', 'strength', true, true, 'Hip bridge variation'),
('Figure-4 (stretch)', 'flexibility', true, true, 'Hip stretching position'),
('Fire Hydrant', 'strength', true, true, 'Hip abduction exercise'),
('Flutter Kicks', 'strength', true, true, 'Core exercise'),
('Foam roll', 'recovery', true, true, 'Self-myofascial release'),
('Foot Drills', 'drill', true, true, 'Foot mechanics drills'),
('Forward lunge', 'strength', true, true, 'Forward stepping lunge'),
('Forward Squat Walk', 'strength', true, true, 'Squat walking forward'),
('Front Squat', 'strength', true, true, 'Front-loaded squat'),
('Front straddle hops', 'plyometric', true, true, 'Forward straddle jumps'),
('Frontal Leg Swings', 'warm_up', true, true, 'Front-to-back leg swings'),
('Full Squat on Ball of Feet', 'strength', true, true, 'Calf-raised squat'),

-- G-H exercises
('Gallops', 'drill', true, true, 'Galloping movement drill'),
('Glute bridge', 'strength', true, true, 'Hip bridge exercise'),
('Glute bridge hip flexion', 'strength', true, true, 'Hip bridge with knee drive'),
('Glute Stretch', 'flexibility', true, true, 'Glute stretching'),
('Glute wall press iso', 'strength', true, true, 'Isometric glute exercise'),
('Good morning', 'strength', true, true, 'Hip hinge movement'),
('Gorilla curls', 'strength', true, true, 'Bicep curl variation'),
('Half Squats', 'strength', true, true, 'Partial range squat'),
('Hammer Hip (I-R) (throw)', 'plyometric', true, true, 'Rotational throwing drill'),
('Hamstring curl (Physio ball leg curls or machine)', 'strength', true, true, 'Hamstring strengthening'),
('Hamstring Scoops', 'flexibility', true, true, 'Dynamic hamstring stretch'),
('Hamstring series (lying on the back exercises and the SL pulls)', 'flexibility', true, true, 'Hamstring stretch series'),
('Hamstring Stretch (Single Leg)', 'flexibility', true, true, 'Single leg hamstring stretch'),
('Hanging leg raises', 'strength', true, true, 'Core strengthening'),
('Heel Sit (stretch)', 'flexibility', true, true, 'Heel sitting stretch'),
('Hex bar jump squats', 'plyometric', true, true, 'Explosive hex bar squats'),
('High Knee Circle Runs', 'drill', true, true, 'High knee running in circles'),
('High Knees', 'drill', true, true, 'High knee running drill'),
('Highland Leg Swing R/L', 'warm_up', true, true, 'Single leg swings'),
('Hill Sprints / Hills', 'running', true, true, 'Uphill running'),
('Hip circles', 'warm_up', true, true, 'Hip mobility exercise'),
('Hip Flexor Stretch (A, R/L)', 'flexibility', true, true, 'Hip flexor stretching'),
('Hip Stretches A', 'flexibility', true, true, 'Hip stretching series'),
('HM over under (Med-ball pop ups) and side drill', 'plyometric', true, true, 'Medicine ball drill'),
('Hop-Bound Bound Combo', 'plyometric', true, true, 'Combination hopping and bounding'),
('Hop-Hop - Between Legs Forward', 'plyometric', true, true, 'Double hop with ball'),
('Hop-Hop - Overhead Back', 'plyometric', true, true, 'Double hop overhead throw'),
('Hurdle drills', 'drill', true, true, 'Hurdle mobility drills'),
('Hurdle Hops', 'plyometric', true, true, 'Hopping over hurdles'),
('Hurdler Seat Switch', 'flexibility', true, true, 'Hurdler stretching position'),
('Hypers w/ Twist', 'strength', true, true, 'Back extension with rotation'),
('Hyper-Ups (Back Extensions)', 'strength', true, true, 'Back strengthening exercise')

ON CONFLICT (name) DO NOTHING; 