-- Continue populating exercise library with remaining system exercises
-- Part 2: I-Z exercises

INSERT INTO public.exercise_library (name, category, is_system_exercise, is_public, description) VALUES

-- I-L exercises
('Impact jumps', 'plyometric', true, true, 'High impact jumping'),
('In Place Pogo Hops', 'plyometric', true, true, 'Stationary hopping'),
('Inch Worms / Walking Inch Worm', 'strength', true, true, 'Walking plank exercise'),
('Incline push up', 'strength', true, true, 'Elevated hand push-up'),
('Jog', 'running', true, true, 'Easy running pace'),
('Jump from easy skip- with landing', 'plyometric', true, true, 'Skip to jump transition'),
('Jump squats', 'plyometric', true, true, 'Explosive squat jumps'),
('Jumping Jacks', 'warm_up', true, true, 'Full body warm-up exercise'),
('Karaoke & Back', 'drill', true, true, 'Lateral running drill'),
('KB tib raises', 'strength', true, true, 'Kettlebell tibialis raises'),
('Knee Hug (stretch)', 'flexibility', true, true, 'Knee to chest stretch'),
('Knee lift Jumps med-ball', 'plyometric', true, true, 'Knee lift jumps with medicine ball'),
('Knee to Chest (Walking)', 'flexibility', true, true, 'Walking knee hugs'),
('Kneeling Accelerations R/L', 'drill', true, true, 'Kneeling start acceleration'),
('Kneeling Pogo Hops', 'plyometric', true, true, 'Kneeling position hops'),
('Kneeling Start R/L', 'drill', true, true, 'Kneeling start position'),
('Kneeling wood chop', 'strength', true, true, 'Kneeling rotational exercise'),
('L-overs', 'drill', true, true, 'Lateral movement drill'),
('Lane hops', 'plyometric', true, true, 'Lane-to-lane hopping'),
('Lat Pulldowns', 'strength', true, true, 'Latissimus dorsi exercise'),
('Lateral Crossover Drill', 'drill', true, true, 'Lateral crossover movement'),
('Lateral hops with step up', 'plyometric', true, true, 'Lateral hopping with elevation'),
('Lateral lunge', 'strength', true, true, 'Side stepping lunge'),
('Lateral Squat Stretches', 'flexibility', true, true, 'Lateral squat stretching'),
('Lateral Squat walk', 'strength', true, true, 'Lateral squat movement'),
('Left Leg Continuous Fast Leg-Walk Back', 'drill', true, true, 'Single leg drill'),
('Leg add ins', 'strength', true, true, 'Hip adduction exercise'),
('Leg Curls', 'strength', true, true, 'Hamstring curl exercise'),
('Leg hug glutes stretch', 'flexibility', true, true, 'Glute stretching'),
('Leg Swings (Front, Side)', 'warm_up', true, true, 'Dynamic leg swinging'),
('Leg Whips', 'drill', true, true, 'Fast leg movement drill'),
('Line hops', 'plyometric', true, true, 'Line-to-line hopping'),
('LJ continuous step&jump / Step & Jump', 'drill', true, true, 'Long jump drill'),
('LJ Pop Up Drill', 'drill', true, true, 'Long jump pop-up drill'),
('Load Ankle (part of Frontside Mechanics cue)', 'drill', true, true, 'Running form cue'),
('Long Jump Drill Gallop', 'drill', true, true, 'Long jump galloping drill'),
('Low knee (drills)', 'drill', true, true, 'Low knee running drill'),
('Low Reach Crunches with Feet Up', 'strength', true, true, 'Core exercise variation'),
('Low Reach Twist Crunches with Feet Up', 'strength', true, true, 'Rotational core exercise'),
('Lunge Chest (throw component)', 'plyometric', true, true, 'Lunge with chest throw'),
('Lunge jump', 'plyometric', true, true, 'Explosive lunge jumps'),
('Lunge knees over toes', 'strength', true, true, 'Deep lunge variation'),
('Lunge side hip toss', 'plyometric', true, true, 'Lunge with lateral throw'),
('Lunge wall toss', 'plyometric', true, true, 'Lunge with wall ball'),
('Lunges (Walking)', 'strength', true, true, 'Walking lunge exercise'),

-- M-P exercises
('Maximums (Sprints at various %, e.g., 60%, 70%, 80%, 90%, 100%)', 'running', true, true, 'Percentage-based sprints'),
('Med ball high knee march', 'plyometric', true, true, 'High knee march with medicine ball'),
('Med ball tosses from lunge on wobble board', 'plyometric', true, true, 'Unstable surface medicine ball exercise'),
('Med-ball leg single full leg drops', 'plyometric', true, true, 'Single leg medicine ball exercise'),
('Med-ball slams', 'plyometric', true, true, 'Medicine ball slamming'),
('Med-ball toss for distance', 'plyometric', true, true, 'Distance medicine ball throw'),
('Medial Kicks', 'drill', true, true, 'Medial leg kicks'),
('Mindful breaths', 'recovery', true, true, 'Breathing exercise'),
('Monster walks', 'strength', true, true, 'Lateral band walks'),
('Mountain Climbers', 'strength', true, true, 'Core and cardio exercise'),
('Neck Rotation', 'warm_up', true, true, 'Neck mobility exercise'),
('Overhead Back (throw)', 'plyometric', true, true, 'Overhead backward throw'),
('Overhead Back Throw', 'plyometric', true, true, 'Overhead backward throwing'),
('Overhead Medball Lateral Hops (L/R leg)', 'plyometric', true, true, 'Lateral hops with overhead ball'),
('Overhead Noodle Drill', 'drill', true, true, 'Overhead noodle drill'),
('Overhead Step (throw component)', 'plyometric', true, true, 'Overhead step throw'),
('Overhead Toss to your Partner Step and THROW', 'plyometric', true, true, 'Partner overhead throw'),
('Overhead Walking Lunges', 'strength', true, true, 'Walking lunges with overhead hold'),
('Overhead wall toss', 'plyometric', true, true, 'Overhead wall ball exercise'),
('Partner lateral squat walks banded', 'strength', true, true, 'Partner lateral squat with band'),
('Partner pass seated med-ball side toss', 'plyometric', true, true, 'Partner seated medicine ball toss'),
('Pelvis Up (part of Frontside Mechanics cue)', 'drill', true, true, 'Running form cue'),
('Physio ball leg curls', 'strength', true, true, 'Hamstring curls on stability ball'),
('Pistol squat (Eccentric)', 'strength', true, true, 'Single leg squat negative'),
('Plank jacks', 'strength', true, true, 'Plank with jumping jacks'),
('Plank jump ins', 'strength', true, true, 'Plank with knee jumps'),
('Plank knee in', 'strength', true, true, 'Plank knee to chest'),
('Plank leg raise', 'strength', true, true, 'Plank with leg lift'),
('Plank roll out', 'strength', true, true, 'Plank with roll out'),
('Plank rotation', 'strength', true, true, 'Rotating plank exercise'),
('Plank step out', 'strength', true, true, 'Plank with step out'),
('Plank to a lunge', 'strength', true, true, 'Plank to lunge transition'),
('Pogo hops', 'plyometric', true, true, 'Vertical hopping exercise'),
('Pop-ups (LJ)', 'drill', true, true, 'Long jump pop-up drill'),
('Power Bounds', 'plyometric', true, true, 'Powerful bounding exercise'),
('Pretzel Right/Left (stretch)', 'flexibility', true, true, 'Pretzel stretching position'),
('Prisoner Squats', 'strength', true, true, 'Hands-behind-head squats'),
('Prone Overhead Back (throw)', 'plyometric', true, true, 'Prone overhead throw'),
('Pull Ups', 'strength', true, true, 'Upper body pulling exercise'),
('Pull overs', 'strength', true, true, 'Chest and lat exercise'),
('Push Press Barbell', 'strength', true, true, 'Barbell push press'),
('Push Press Dumbbell', 'strength', true, true, 'Dumbbell push press'),
('Push up crunch', 'strength', true, true, 'Push-up to crunch combination'),
('Push Up Sky Dive', 'strength', true, true, 'Dynamic push-up variation'),
('Push Ups', 'strength', true, true, 'Standard push-up exercise'),
('Pushup Stance Leg Lifts', 'strength', true, true, 'Push-up position leg lifts'),
('Pushup Walk', 'strength', true, true, 'Walking in push-up position'),

-- Q-S exercises
('Quad Stretch (Walking, Static)', 'flexibility', true, true, 'Quadriceps stretching'),
('Quick Feet', 'drill', true, true, 'Fast foot movement drill'),
('Reactive Box Jumps', 'plyometric', true, true, 'Reactive jumping exercise'),
('Rest (as part of interval workouts)', 'rest_interval', true, true, 'Recovery interval'),
('Reverse crunch', 'strength', true, true, 'Reverse abdominal exercise'),
('Reverse lunge', 'strength', true, true, 'Backward stepping lunge'),
('Reverse Med Ball Toss', 'plyometric', true, true, 'Backward medicine ball throw'),
('Right Leg Continuous Fast Leg-Walk Back', 'drill', true, true, 'Single leg drill'),
('Rocket jumps', 'plyometric', true, true, 'Explosive vertical jumps'),
('Roll on lax ball', 'recovery', true, true, 'Lacrosse ball rolling'),
('Rotary A-Skips in Place R/L', 'drill', true, true, 'Stationary A-skip drill'),
('Run (Interval, Sprint-Float-Sprint, various distances)', 'running', true, true, 'Various running exercises'),
('Run Run Jump Drill (L-R)', 'drill', true, true, 'Run-run-jump drill'),
('Russian Hamstring', 'strength', true, true, 'Eccentric hamstring exercise'),
('Russian twist', 'strength', true, true, 'Rotational core exercise'),
('Sagittal Leg Swings', 'warm_up', true, true, 'Forward-back leg swings'),
('Scissor Jump / Scisscor jumps', 'plyometric', true, true, 'Alternating leg jumps'),
('Scorpions', 'flexibility', true, true, 'Dynamic stretching exercise'),
('Seated Arm Pull (stretch)', 'flexibility', true, true, 'Seated arm stretching'),
('Seated figure 4 with rotations', 'flexibility', true, true, 'Seated hip stretch with rotation'),
('Seated Hip (throw)', 'plyometric', true, true, 'Seated throwing exercise'),
('Self hugs (open and close arms)', 'warm_up', true, true, 'Arm swinging warm-up'),
('Side A-Skips', 'drill', true, true, 'Lateral A-skip drill'),
('Side Foot Toe Raises', 'strength', true, true, 'Lateral foot strengthening'),
('Side lying hip abduction', 'strength', true, true, 'Hip strengthening exercise'),
('Side planks', 'strength', true, true, 'Lateral core strengthening'),
('Side plank rotation', 'strength', true, true, 'Rotating side plank'),
('Side plank Bottom Leg Lifts', 'strength', true, true, 'Side plank with bottom leg lift'),
('Side Plank Hip Thrusts', 'strength', true, true, 'Side plank with hip thrust'),
('Side plank on Hand Bottom Leg Lifts', 'strength', true, true, 'Hand side plank with bottom leg lift'),
('Side Plank on Hand Top Leg Lifts', 'strength', true, true, 'Hand side plank with top leg lift'),
('Side Plank Top Leg Lifts', 'strength', true, true, 'Side plank with top leg lift'),
('Side Shuffle', 'drill', true, true, 'Lateral shuffling drill'),
('Side sled pulls', 'strength', true, true, 'Lateral sled pulling'),
('Side star planks', 'strength', true, true, 'Star position side plank'),
('Side step ups', 'strength', true, true, 'Lateral step-up exercise'),
('Side straddle hops', 'plyometric', true, true, 'Lateral straddle jumps'),
('Side to Side Arm Swings', 'warm_up', true, true, 'Lateral arm swinging'),
('Single Leg Bounds', 'plyometric', true, true, 'Single leg bounding'),
('Single Leg Curls', 'strength', true, true, 'Single leg hamstring curls'),
('Single Leg Hamstring (stretch)', 'flexibility', true, true, 'Single leg hamstring stretch'),
('Single Leg Hops (SL HOPS)', 'plyometric', true, true, 'Single leg hopping'),
('Single Leg Skipovers', 'drill', true, true, 'Single leg skip-over drill'),
('Single Leg Squats', 'strength', true, true, 'Single leg squat exercise'),
('Single Leg Static/Dynamic Skipovers', 'drill', true, true, 'Single leg skip-over variations'),
('Single Leg Tuck Jumps (SL Tuck Jumps)', 'plyometric', true, true, 'Single leg tuck jumps'),
('Single leg wall sit', 'strength', true, true, 'Single leg wall sit'),
('Sit ups tossing', 'strength', true, true, 'Sit-ups with ball toss'),
('Ski jumps', 'plyometric', true, true, 'Lateral ski jumps'),
('Skip Lunges (Forward, Backward)', 'plyometric', true, true, 'Skipping lunge variations'),
('Skipovers Left Lead Leg', 'drill', true, true, 'Left leg lead skip-overs'),
('Skipovers Right Lead Leg', 'drill', true, true, 'Right leg lead skip-overs'),
('Skips for distance', 'drill', true, true, 'Distance-focused skipping'),
('Skips for height', 'drill', true, true, 'Height-focused skipping'),
('SL Butt Kicks', 'drill', true, true, 'Single leg butt kicks'),
('SL Cycle Hops', 'plyometric', true, true, 'Single leg cycling hops'),
('SL Lateral Hops', 'plyometric', true, true, 'Single leg lateral hops'),
('SL Pogo Jumps', 'plyometric', true, true, 'Single leg pogo jumps'),
('Sled push', 'strength', true, true, 'Sled pushing exercise'),
('Sleds (forward, backward, sideways)', 'strength', true, true, 'Various sled exercises'),
('Snatch (Dumbbell, Barbell, floor, knee, thigh)', 'strength', true, true, 'Olympic snatch variations'),
('Snatch Pulls', 'strength', true, true, 'Snatch pulling phase'),
('Spanish squat', 'strength', true, true, 'Squat variation'),
('Speed Bounds', 'plyometric', true, true, 'Fast bounding exercise'),
('Speed Skaters', 'plyometric', true, true, 'Lateral skating movement'),
('Spinal Roll', 'flexibility', true, true, 'Spinal mobility exercise'),
('Split Jumps', 'plyometric', true, true, 'Split position jumps'),
('Split Snatch', 'strength', true, true, 'Split position snatch'),
('Split Stretch', 'flexibility', true, true, 'Split position stretching'),
('Sprint (Maximums, Full Approaches, etc.)', 'running', true, true, 'Maximum speed running'),
('Squat Chest (throw)', 'plyometric', true, true, 'Squat with chest throw'),
('Squat Jumps', 'plyometric', true, true, 'Explosive squat jumps'),
('Squat pulses', 'strength', true, true, 'Pulsing squat exercise'),
('Squat Toe Raises', 'strength', true, true, 'Squat with calf raise'),
('Squats', 'strength', true, true, 'Basic squat exercise'),
('Stadium Circuit / Stadium Stairs (Singles, Doubles etc.)', 'running', true, true, 'Stadium stair exercises'),
('Standing Accelerations (2 pt., 3 pt.)', 'drill', true, true, 'Standing start accelerations'),
('Standing Ankle Dorsi-Flexion', 'strength', true, true, 'Ankle dorsiflexion exercise'),
('Standing Calf R/L (stretch)', 'flexibility', true, true, 'Standing calf stretch'),
('Standing Good Mornings', 'strength', true, true, 'Standing hip hinge'),
('Standing LJ / Broad Jump', 'plyometric', true, true, 'Standing long jump'),
('Standing Overhead Forward (throw)', 'plyometric', true, true, 'Standing overhead throw'),
('Standing Triple Jump', 'plyometric', true, true, 'Standing triple jump'),
('Star Jumps', 'plyometric', true, true, 'Star position jumps'),
('Stationary High knees', 'drill', true, true, 'Stationary high knee drill'),
('Steering Drill', 'drill', true, true, 'Direction change drill'),
('Step Over the Opposite Knee (part of Frontside Mechanics cue)', 'drill', true, true, 'Running form cue'),
('Step ups', 'strength', true, true, 'Step-up exercise'),
('Straddle jumps', 'plyometric', true, true, 'Straddle position jumps'),
('Straddle Stretch Middle/Right/Left', 'flexibility', true, true, 'Straddle stretching positions'),
('Straight Leg Bounds', 'plyometric', true, true, 'Straight leg bounding'),
('Straight Leg Deadlifts', 'strength', true, true, 'Straight leg deadlift'),
('Straight Leg Shuffle', 'drill', true, true, 'Straight leg shuffling'),
('Stride', 'running', true, true, 'Striding exercise'),
('Suitcase Carry', 'strength', true, true, 'Unilateral carry exercise'),
('Suitcase crunches', 'strength', true, true, 'Suitcase position crunches'),
('Sumo Squats', 'strength', true, true, 'Wide stance squat'),
('Superman', 'strength', true, true, 'Back extension exercise'),
('Superman w/ Twist', 'strength', true, true, 'Back extension with rotation'),
('Swing Arms from the Shoulders (part of Frontside Mechanics cue)', 'drill', true, true, 'Running form cue'),

-- T-W exercises
('TJ 6 step Hop and Step', 'drill', true, true, 'Triple jump drill'),
('TIB Raises / Tib raise', 'strength', true, true, 'Tibialis anterior strengthening'),
('Tight High Knee''s Rotary', 'drill', true, true, 'Tight high knee drill'),
('Toe Touches', 'flexibility', true, true, 'Forward bending stretch'),
('Toe-Up (part of Frontside Mechanics cue)', 'drill', true, true, 'Running form cue'),
('Trail Leg Circles', 'drill', true, true, 'Hurdle trail leg drill'),
('Tuck Jumps', 'plyometric', true, true, 'Knee tuck jumps'),
('Turnarounds', 'drill', true, true, 'Direction change drill'),
('Twist Lunges', 'strength', true, true, 'Rotational lunge exercise'),
('Underhand tosses (Medicine Ball)', 'plyometric', true, true, 'Underhand medicine ball throw'),
('Up down planks', 'strength', true, true, 'Plank up-down exercise'),
('V Ups / v-ups', 'strength', true, true, 'V-position sit-ups'),
('V-sit pass the ball', 'strength', true, true, 'V-sit with ball passing'),
('Vertical Jump', 'plyometric', true, true, 'Maximum vertical jump'),
('Walk on heels', 'drill', true, true, 'Heel walking drill'),
('Walk on inside/outside of foot (forward/backward)', 'drill', true, true, 'Foot position walking'),
('Walk on toes', 'drill', true, true, 'Toe walking drill'),
('Walkovers Left/Right Lead Leg', 'flexibility', true, true, 'Dynamic leg walkovers'),
('Walking Inch Worm (see Inch Worms)', 'strength', true, true, 'Walking plank exercise'),
('Walking Knee to Chest', 'flexibility', true, true, 'Walking knee hugs'),
('Walking Overhead Med Hurdles', 'plyometric', true, true, 'Walking with overhead ball'),
('Walking opposite elbow to knee', 'flexibility', true, true, 'Cross-body walking stretch'),
('Walking opposite elbow to knee with lunge', 'flexibility', true, true, 'Cross-body lunge stretch'),
('Walking on heels (sprinting arms)', 'drill', true, true, 'Heel walk with arm action'),
('Walking on toes (sprinting arms)', 'drill', true, true, 'Toe walk with arm action'),
('Walking quad stretch', 'flexibility', true, true, 'Walking quadriceps stretch'),
('Walking stretches - quads, hams, glutes', 'flexibility', true, true, 'Walking stretch series'),
('Walking Lunges', 'strength', true, true, 'Walking lunge exercise'),
('Wall drill calf raises', 'strength', true, true, 'Wall-supported calf raises'),
('Wall toss', 'plyometric', true, true, 'Wall ball exercise'),
('Water Break / Electrolyte Break (activity, not exercise)', 'rest_interval', true, true, 'Hydration break'),
('Weave (running drill)', 'drill', true, true, 'Weaving running drill'),
('Wharton rope stretches', 'flexibility', true, true, 'Rope-assisted stretching'),
('Wicket Speed Dev (likely a drill series)', 'drill', true, true, 'Wicket speed development'),
('Wideouts', 'drill', true, true, 'Wide step drill'),
('Windmill', 'flexibility', true, true, 'Windmill stretching exercise'),
('Ws (drill)', 'drill', true, true, 'W-position drill')

ON CONFLICT (name) DO NOTHING; 