-- Insert all exercises from the comprehensive list
INSERT INTO public.exercise_library (name, category, is_system_exercise, description) VALUES
-- A exercises
('10-5-5 (Drill)', 'drill', true, 'Track and field drill'),
('180 Degree Jumps (180s)', 'plyometric', true, 'Rotational jumping exercise'),
('3 Pt. Stance Acceleration R/L', 'drill', true, 'Three-point stance acceleration drill'),
('3 Pt. Stance', 'drill', true, 'Three-point starting stance'),
('4 Bounds into strides', 'plyometric', true, 'Bounding exercise transitioning to strides'),
('4 way cable (Cable 4-way hips)', 'strength', true, 'Hip strengthening with cable machine'),
('90/90 Hip Switches', 'flexibility', true, 'Hip mobility exercise'),
('A Skip w-Clap (Backward Alternating)', 'drill', true, 'A-skip variation with clapping'),
('A Skips / A-Switches', 'drill', true, 'Fundamental running drill'),
('Accelerations (General, e.g., 2 pt. Standing, 3 pt. Standing, Kneeling)', 'running', true, 'Various acceleration techniques'),
('Adductor Stretch', 'flexibility', true, 'Inner thigh stretching'),
('Alternate Dynamic Walkovers', 'flexibility', true, 'Dynamic leg swing exercise'),
('Alt Highland Leg Swings', 'warm_up', true, 'Alternating leg swing warm-up'),
('Ankle Bounce', 'warm_up', true, 'Ankle mobility exercise'),
('Ankle Rotation', 'warm_up', true, 'Ankle mobility and strengthening'),
('Ankling', 'drill', true, 'Foot and ankle running drill'),
('Arm Across Skips', 'drill', true, 'Skipping with arm movement'),
('Arm Circle Skips', 'drill', true, 'Skipping with arm circles'),
('Arm circles (backwards and forward)', 'warm_up', true, 'Shoulder warm-up exercise'),
('Around the world on tape', 'drill', true, 'Agility drill on line/tape'),

-- B exercises
('B Skips', 'drill', true, 'Running drill progression'),
('Back Extensions (Hypers)', 'strength', true, 'Lower back strengthening'),
('Back Pedal', 'drill', true, 'Backward running drill'),
('Back Plank Hip Arch', 'strength', true, 'Core strengthening exercise'),
('Back Plank Leg Lifts', 'strength', true, 'Core and glute strengthening'),
('Back rolls', 'flexibility', true, 'Spinal mobility exercise'),
('Back Squats', 'strength', true, 'Compound leg strengthening exercise'),
('Backward A Switches', 'drill', true, 'Reverse A-skip drill'),
('Backward Lunges', 'strength', true, 'Reverse lunge exercise'),
('Backward pogos', 'plyometric', true, 'Backward hopping exercise'),
('Backward Skips', 'drill', true, 'Backward skipping drill'),
('Backward Squat Walk', 'strength', true, 'Squat walking backward'),
('Band internal and external rotation', 'strength', true, 'Shoulder rotation with resistance band'),
('Banded squat Jumps', 'plyometric', true, 'Jump squats with resistance band'),
('Barbell Hang Clean', 'strength', true, 'Olympic lifting movement'),
('Barbell Single Leg Clean', 'strength', true, 'Single leg Olympic lift variation'),
('Bear crawl pull throughs', 'strength', true, 'Full body crawling exercise'),
('Bench Press', 'strength', true, 'Upper body pushing exercise'),
('Bentover Rows', 'strength', true, 'Back strengthening exercise'),
('Between the Legs forward (throw)', 'plyometric', true, 'Medicine ball throw'),
('Bicycle with Rollover', 'strength', true, 'Core exercise variation'),
('Bikes (core exercise)', 'strength', true, 'Abdominal exercise'),
('Bird dog', 'strength', true, 'Core stability exercise'),
('Bleachers (running)', 'running', true, 'Stadium stair running'),
('Block Thigh Parallel (part of Frontside Mechanics cue)', 'drill', true, 'Running form drill'),
('Body rotations', 'warm_up', true, 'Torso rotation warm-up'),
('Bounds for Distance', 'plyometric', true, 'Horizontal bounding'),
('Bounds for Height', 'plyometric', true, 'Vertical bounding'),
('Bounds', 'plyometric', true, 'General bounding exercise'),
('Box - Between Legs Forward', 'plyometric', true, 'Medicine ball throw variation'),
('Box - Overhead Back', 'plyometric', true, 'Overhead medicine ball throw'),
('Box Jumps', 'plyometric', true, 'Jumping onto elevated platform'),
('Bridges to Pike', 'strength', true, 'Hip bridge to pike movement'),
('Broad Jump (Standing Long Jump / SLJ)', 'plyometric', true, 'Horizontal jumping exercise'),
('Bulgarian split squat', 'strength', true, 'Single leg squat variation'),
('Bunny hops', 'plyometric', true, 'Double leg hopping'),
('Burpee Pull Up', 'strength', true, 'Compound burpee with pull-up'),
('Burpees', 'strength', true, 'Full body exercise'),
('Butt Kick Jumps', 'plyometric', true, 'Jumping butt kicks'),
('Butt Kicks', 'drill', true, 'Running drill'),
('Butterfly (stretch)', 'flexibility', true, 'Hip flexibility stretch'),

-- C exercises
('C Skips', 'drill', true, 'Advanced running drill'),
('Calf raises on slant board', 'strength', true, 'Calf strengthening on incline'),
('Calf raises with lax ball', 'strength', true, 'Calf raises with lacrosse ball'),
('Calf stretch in push up position', 'flexibility', true, 'Calf stretching variation'),
('Calf Stretch (Standing R/L)', 'flexibility', true, 'Standing calf stretch'),
('Chair drill (for LJ/TJ)', 'drill', true, 'Long jump/Triple jump drill'),
('Chess passes (Medicine Ball)', 'plyometric', true, 'Medicine ball passing drill'),
('Chest Hang (stretch)', 'flexibility', true, 'Chest stretching exercise'),
('Chest Over Thigh (part of Frontside Mechanics cue)', 'drill', true, 'Running form cue'),
('Chin ups', 'strength', true, 'Upper body pulling exercise'),
('Circle Drill (HJ - pushing off the curve)', 'drill', true, 'High jump technique drill'),
('Circuit Paired Run', 'running', true, 'Partnered running drill'),
('Clams / Clamshells', 'strength', true, 'Hip strengthening exercise'),
('Clean (floor, knee, thigh)', 'strength', true, 'Olympic lifting variations'),
('Clean & Jerk', 'strength', true, 'Olympic lifting movement'),
('Clean pulls', 'strength', true, 'Olympic lift pulling phase'),
('Closed Everted Toe Squats', 'strength', true, 'Squat variation with foot position'),
('Cocked Foot (part of Frontside Mechanics cue)', 'drill', true, 'Running form technique'),
('Combo Bounds', 'plyometric', true, 'Combination bounding exercise'),
('Continuous 3 steps pop-ups', 'plyometric', true, 'Continuous jumping drill'),
('Cool-Down Stretches (general category, specific ones listed)', 'cool_down', true, 'General cool-down stretching'),
('Core exercises (general)', 'strength', true, 'General abdominal strengthening'),
('Cossack Extensions', 'flexibility', true, 'Deep lateral lunge stretch'),
('Cossack squat', 'strength', true, 'Lateral squat movement'),
('Cracks with med-ball', 'plyometric', true, 'Medicine ball exercise'),
('Crossover hops', 'plyometric', true, 'Lateral hopping exercise'),
('Crossover Runs', 'drill', true, 'Lateral running drill'),
('Crossover Step-Ups', 'strength', true, 'Lateral step-up exercise'),
('Crunches', 'strength', true, 'Abdominal exercise'),
('Crunches w/ Twist', 'strength', true, 'Rotational abdominal exercise'),
('Curtsy lunge', 'strength', true, 'Reverse diagonal lunge'),
('Curve work (HJ drills)', 'drill', true, 'High jump curve running'),

-- D exercises
('DB Calf Raises', 'strength', true, 'Dumbbell calf raises'),
('DB RDL', 'strength', true, 'Dumbbell Romanian deadlift'),
('DB Seated Jumps', 'plyometric', true, 'Seated jump with dumbbells'),
('DB Step Ups (keep toe dorsiflex)', 'strength', true, 'Dumbbell step-ups'),
('Dead bug', 'strength', true, 'Core stability exercise'),
('Dead lift', 'strength', true, 'Compound pulling exercise'),
('Decline push up', 'strength', true, 'Elevated feet push-up'),
('Deep Body Squats', 'strength', true, 'Deep squat movement'),
('Deep Squat (stretch)', 'flexibility', true, 'Deep squat hold'),
('Depth Drops / Depth Jumps', 'plyometric', true, 'Drop jumping exercise'),
('Diagonal hops', 'plyometric', true, 'Multi-directional hopping'),
('Dips', 'strength', true, 'Upper body pushing exercise'),
('DL Lateral Hops', 'plyometric', true, 'Double leg lateral hops'),
('Donkey kicks', 'strength', true, 'Glute strengthening exercise'),
('Double A Switches', 'drill', true, 'Double A-skip drill'),
('Double Double TJ / Double Double TJ Drill', 'drill', true, 'Triple jump technique drill'),
('Double Knee Tucks', 'plyometric', true, 'Double knee jumping exercise'),
('Double Leg Backward', 'plyometric', true, 'Backward double leg hops'),
('Double Leg Bounds', 'plyometric', true, 'Double leg bounding'),
('Double Leg Forward', 'plyometric', true, 'Forward double leg hops'),
('Drop Jumps', 'plyometric', true, 'Drop and jump exercise'),
('Dumbbell Hang Clean', 'strength', true, 'Dumbbell Olympic lift'),
('Dumbbell Snatch', 'strength', true, 'Dumbbell Olympic lift'),
('Dynamic Flexibility (general category of exercises)', 'warm_up', true, 'Dynamic warm-up movements'),
('Dynamic Scissors', 'flexibility', true, 'Dynamic leg swinging'),

-- E-F exercises
('Eagles', 'flexibility', true, 'Stretching exercise'),
('Eccentric pistol squats', 'strength', true, 'Single leg squat negative'),
('Elbow to Knee Lunge', 'flexibility', true, 'Dynamic lunge stretch'),
('Eversion with band', 'strength', true, 'Ankle strengthening with band'),
('Fast A Switches Rotary (No Bounce / Two Bounces)', 'drill', true, 'Fast A-skip variations'),
('Fast Five A Switches Rotary (Two Bounces)', 'drill', true, 'Fast A-skip drill'),
('Fast leg', 'drill', true, 'Fast leg cycling drill'),
('Fast Leg Continuous R/L', 'drill', true, 'Continuous fast leg drill'),
('Fast Leg Rotary Cycle R/L Only', 'drill', true, 'Single leg fast cycling'),
('Fast Leg Rotary Double R/L Only', 'drill', true, 'Double leg fast cycling'),
('Figure 4 bridge', 'strength', true, 'Hip bridge variation'),
('Figure-4 (stretch)', 'flexibility', true, 'Hip stretching position'),
('Fire Hydrant', 'strength', true, 'Hip abduction exercise'),
('Flutter Kicks', 'strength', true, 'Core strengthening exercise'),
('Foam roll', 'recovery', true, 'Self-myofascial release'),
('Foot Drills', 'drill', true, 'Foot and ankle drills'),
('Forward lunge', 'strength', true, 'Forward stepping lunge'),
('Forward Squat Walk', 'strength', true, 'Squat walking forward'),
('Front Squat', 'strength', true, 'Front-loaded squat'),
('Front straddle hops', 'plyometric', true, 'Forward straddle jumping'),
('Frontal Leg Swings', 'warm_up', true, 'Forward and back leg swings'),
('Full Squat on Ball of Feet', 'strength', true, 'Calf-raised squat'),

-- G-H exercises
('Gallops', 'drill', true, 'Galloping running drill'),
('Glute bridge', 'strength', true, 'Hip extension exercise'),
('Glute bridge hip flexion', 'strength', true, 'Glute bridge with leg movement'),
('Glute Stretch', 'flexibility', true, 'Glute stretching'),
('Glute wall press iso', 'strength', true, 'Isometric glute exercise'),
('Good morning', 'strength', true, 'Hip hinge exercise'),
('Gorilla curls', 'strength', true, 'Bicep exercise variation'),
('Half Squats', 'strength', true, 'Partial range squat'),
('Hammer Hip (I-R) (throw)', 'plyometric', true, 'Rotational throwing movement'),
('Hamstring curl (Physio ball leg curls or machine)', 'strength', true, 'Hamstring strengthening'),
('Hamstring Scoops', 'flexibility', true, 'Hamstring stretching movement'),
('Hamstring series (lying on the back exercises and the SL pulls)', 'flexibility', true, 'Hamstring stretch series'),
('Hamstring Stretch (Single Leg)', 'flexibility', true, 'Single leg hamstring stretch'),
('Hanging leg raises', 'strength', true, 'Abdominal strengthening'),
('Heel Sit (stretch)', 'flexibility', true, 'Heel sitting stretch'),
('Hex bar jump squats', 'plyometric', true, 'Jump squats with hex bar'),
('High Knee Circle Runs', 'drill', true, 'High knee running in circles'),
('High Knees', 'drill', true, 'High knee running drill'),
('Highland Leg Swing R/L', 'warm_up', true, 'Single leg swinging'),
('Hill Sprints / Hills', 'running', true, 'Uphill running'),
('Hip circles', 'warm_up', true, 'Hip mobility exercise'),
('Hip Flexor Stretch (A, R/L)', 'flexibility', true, 'Hip flexor stretching'),
('Hip Stretches A', 'flexibility', true, 'Hip stretching series'),
('HM over under (Med-ball pop ups) and side drill', 'plyometric', true, 'Medicine ball drill'),
('Hop-Bound Bound Combo', 'plyometric', true, 'Combination hopping and bounding'),
('Hop-Hop - Between Legs Forward', 'plyometric', true, 'Double hop with ball'),
('Hop-Hop - Overhead Back', 'plyometric', true, 'Double hop overhead throw'),
('Hurdle drills', 'drill', true, 'Hurdle mobility drills'),
('Hurdle Hops', 'plyometric', true, 'Hopping over hurdles'),
('Hurdler Seat Switch', 'flexibility', true, 'Hurdler stretching position'),
('Hypers w/ Twist', 'strength', true, 'Back extension with rotation'),
('Hyper-Ups (Back Extensions)', 'strength', true, 'Back strengthening exercise'),

-- I-L exercises
('Impact jumps', 'plyometric', true, 'High impact jumping'),
('In Place Pogo Hops', 'plyometric', true, 'Stationary hopping'),
('Inch Worms / Walking Inch Worm', 'strength', true, 'Walking plank exercise'),
('Incline push up', 'strength', true, 'Elevated hand push-up'),
('Jog', 'running', true, 'Easy running pace'),
('Jump from easy skip- with landing', 'plyometric', true, 'Skip to jump transition'),
('Jump squats', 'plyometric', true, 'Explosive squat jumps'),
('Jumping Jacks', 'warm_up', true, 'Full body warm-up exercise'),
('Karaoke & Back', 'drill', true, 'Lateral running drill'),
('KB tib raises', 'strength', true, 'Kettlebell tibialis raises'),
('Knee Hug (stretch)', 'flexibility', true, 'Knee to chest stretch'),
('Knee lift Jumps med-ball', 'plyometric', true, 'Knee lift jumps with medicine ball'),
('Knee to Chest (Walking)', 'flexibility', true, 'Walking knee hugs'),
('Kneeling Accelerations R/L', 'drill', true, 'Kneeling start acceleration'),
('Kneeling Pogo Hops', 'plyometric', true, 'Kneeling hopping exercise'),
('Kneeling Start R/L', 'drill', true, 'Kneeling starting position'),
('Kneeling wood chop', 'strength', true, 'Rotational core exercise'),
('L-overs', 'plyometric', true, 'Lateral stepping exercise'),
('Lane hops', 'plyometric', true, 'Lane line hopping drill'),
('Lat Pulldowns', 'strength', true, 'Latissimus dorsi exercise'),
('Lateral Crossover Drill', 'drill', true, 'Lateral movement drill'),
('Lateral hops with step up', 'plyometric', true, 'Combined lateral hop and step'),
('Lateral lunge', 'strength', true, 'Side stepping lunge'),
('Lateral Squat Stretches', 'flexibility', true, 'Side squat stretching'),
('Lateral Squat walk', 'strength', true, 'Side stepping squat walk'),
('Left Leg Continuous Fast Leg-Walk Back', 'drill', true, 'Single leg drill'),
('Leg add ins', 'strength', true, 'Hip adduction exercise'),
('Leg Curls', 'strength', true, 'Hamstring strengthening'),
('Leg hug glutes stretch', 'flexibility', true, 'Glute stretching with leg hug'),
('Leg Swings (Front, Side)', 'warm_up', true, 'Dynamic leg swinging'),
('Leg Whips', 'drill', true, 'Fast leg movement drill'),
('Lift (general category for weightlifting)', 'strength', true, 'General weightlifting'),
('Line hops', 'plyometric', true, 'Line hopping drill'),
('LJ continuous step&jump / Step & Jump', 'drill', true, 'Long jump drill'),
('LJ Pop Up Drill', 'drill', true, 'Long jump takeoff drill'),
('Load Ankle (part of Frontside Mechanics cue)', 'drill', true, 'Running form cue'),
('Long Jump Drill Gallop', 'drill', true, 'Long jump approach drill'),
('Low knee (drills)', 'drill', true, 'Low knee running drill'),
('Low Reach Crunches with Feet Up', 'strength', true, 'Abdominal exercise variation'),
('Low Reach Twist Crunches with Feet Up', 'strength', true, 'Rotational ab exercise'),
('Lunge Chest (throw component)', 'plyometric', true, 'Lunge with chest throw'),
('Lunge jump', 'plyometric', true, 'Explosive lunge jumps'),
('Lunge knees over toes', 'strength', true, 'Deep lunge variation'),
('Lunge side hip toss', 'plyometric', true, 'Lunge with lateral throw'),
('Lunge wall toss', 'plyometric', true, 'Lunge with wall ball'),
('Lunges (Walking)', 'strength', true, 'Walking lunge exercise'),

-- M-P exercises
('Maximums (Sprints at various %, e.g., 60%, 70%, 80%, 90%, 100%)', 'running', true, 'Percentage-based sprints'),
('Med ball high knee march', 'strength', true, 'High knees with medicine ball'),
('Med ball tosses from lunge on wobble board', 'plyometric', true, 'Balance and power exercise'),
('Med-ball leg single full leg drops', 'plyometric', true, 'Single leg drop with ball'),
('Med-ball slams', 'plyometric', true, 'Medicine ball slamming'),
('Med-ball toss for distance', 'plyometric', true, 'Distance throwing with medicine ball'),
('Medial Kicks', 'drill', true, 'Inside leg kicking drill'),
('Mindful breaths', 'recovery', true, 'Breathing exercise'),
('Monster walks', 'strength', true, 'Wide stance walking'),
('Mountain Climbers', 'strength', true, 'Core and cardio exercise'),
('Neck Rotation', 'warm_up', true, 'Neck mobility exercise'),
('Overhead Back (throw)', 'plyometric', true, 'Overhead backward throw'),
('Overhead Back Throw', 'plyometric', true, 'Overhead backward throwing'),
('Overhead Medball Lateral Hops (L/R leg)', 'plyometric', true, 'Lateral hops with overhead ball'),
('Overhead Noodle Drill', 'drill', true, 'Overhead arm drill'),
('Overhead Step (throw component)', 'plyometric', true, 'Step with overhead throw'),
('Overhead Toss to your Partner Step and THROW', 'plyometric', true, 'Partner overhead throwing'),
('Overhead Walking Lunges', 'strength', true, 'Lunges with overhead weight'),
('Overhead wall toss', 'plyometric', true, 'Overhead wall ball exercise'),
('Partner lateral squat walks banded', 'strength', true, 'Partner squat walks with band'),
('Partner pass seated med-ball side toss', 'plyometric', true, 'Seated partner ball toss'),
('Pelvis Up (part of Frontside Mechanics cue)', 'drill', true, 'Running form cue'),
('Physio ball leg curls', 'strength', true, 'Hamstring curls on exercise ball'),
('Pistol squat (Eccentric)', 'strength', true, 'Single leg squat negative'),
('Plank jacks', 'strength', true, 'Plank with jumping jack legs'),
('Plank jump ins', 'strength', true, 'Plank to squat jumps'),
('Plank knee in', 'strength', true, 'Plank with knee drives'),
('Plank leg raise', 'strength', true, 'Plank with leg lifts'),
('Plank roll out', 'strength', true, 'Rolling plank exercise'),
('Plank rotation', 'strength', true, 'Rotating plank exercise'),
('Plank step out', 'strength', true, 'Plank with step outs'),
('Plank to a lunge', 'strength', true, 'Plank to lunge transition'),
('Plank', 'strength', true, 'Core stabilization exercise'),
('Pogo hops', 'plyometric', true, 'Bouncing hop exercise'),
('Pop-ups (LJ)', 'drill', true, 'Long jump takeoff drill'),
('Power Bounds', 'plyometric', true, 'Explosive bounding exercise'),
('Pretzel Right/Left (stretch)', 'flexibility', true, 'Pretzel stretching position'),
('Prisoner Squats', 'strength', true, 'Squats with hands behind head'),
('Prone Overhead Back (throw)', 'plyometric', true, 'Prone overhead throw'),
('Pull Ups', 'strength', true, 'Upper body pulling exercise'),
('Pull overs', 'strength', true, 'Latissimus dorsi exercise'),
('Push Press Barbell', 'strength', true, 'Overhead pressing with legs'),
('Push Press Dumbbell', 'strength', true, 'Dumbbell overhead press'),
('Push up crunch', 'strength', true, 'Combined push-up and crunch'),
('Push Up Sky Dive', 'strength', true, 'Dynamic push-up variation'),
('Push Ups', 'strength', true, 'Upper body pushing exercise'),
('Pushup Stance Leg Lifts', 'strength', true, 'Leg lifts in push-up position'),
('Pushup Walk', 'strength', true, 'Walking in push-up position'),

-- Q-S exercises
('Quad Stretch (Walking, Static)', 'flexibility', true, 'Quadriceps stretching'),
('Quick Feet', 'drill', true, 'Fast foot movement drill'),
('Reactive Box Jumps', 'plyometric', true, 'Reactive jumping exercise'),
('Rest (as part of interval workouts)', 'rest_interval', true, 'Recovery interval'),
('Reverse crunch', 'strength', true, 'Reverse abdominal exercise'),
('Reverse lunge', 'strength', true, 'Backward stepping lunge'),
('Reverse Med Ball Toss', 'plyometric', true, 'Backward medicine ball throw'),
('Right Leg Continuous Fast Leg-Walk Back', 'drill', true, 'Single leg drill'),
('Rocket jumps', 'plyometric', true, 'Explosive vertical jumps'),
('Roll on lax ball', 'recovery', true, 'Lacrosse ball rolling'),
('Rotary A-Skips in Place R/L', 'drill', true, 'Stationary A-skip drill'),
('Run (Interval, Sprint-Float-Sprint, various distances)', 'running', true, 'Various running exercises'),
('Run Run Jump Drill (L-R)', 'drill', true, 'Run-run-jump drill'),
('Russian Hamstring', 'strength', true, 'Eccentric hamstring exercise'),
('Russian twist', 'strength', true, 'Rotational core exercise'),
('Sagittal Leg Swings', 'warm_up', true, 'Forward-back leg swings'),
('Scissor Jump / Scisscor jumps', 'plyometric', true, 'Alternating leg jumps'),
('Scorpions', 'flexibility', true, 'Dynamic stretching exercise'),
('Seated Arm Pull (stretch)', 'flexibility', true, 'Seated arm stretching'),
('Seated figure 4 with rotations', 'flexibility', true, 'Seated hip stretch with rotation'),
('Seated Hip (throw)', 'plyometric', true, 'Seated throwing exercise'),
('Self hugs (open and close arms)', 'warm_up', true, 'Arm swinging warm-up'),
('Side A-Skips', 'drill', true, 'Lateral A-skip drill'),
('Side Foot Toe Raises', 'strength', true, 'Lateral foot strengthening'),
('Side lying hip abduction', 'strength', true, 'Hip strengthening exercise'),
('Side planks', 'strength', true, 'Lateral core strengthening'),
('Side plank rotation', 'strength', true, 'Rotating side plank'),
('Side plank Bottom Leg Lifts', 'strength', true, 'Side plank with bottom leg lift'),
('Side Plank Hip Thrusts', 'strength', true, 'Side plank with hip movement'),
('Side plank on Hand Bottom Leg Lifts', 'strength', true, 'Hand side plank with leg lift'),
('Side Plank on Hand Top Leg Lifts', 'strength', true, 'Hand side plank top leg lift'),
('Side Plank Top Leg Lifts', 'strength', true, 'Side plank with top leg lift'),
('Side Shuffle', 'drill', true, 'Lateral shuffling drill'),
('Side sled pulls', 'strength', true, 'Lateral sled pulling'),
('Side star planks', 'strength', true, 'Side plank variation'),
('Side step ups', 'strength', true, 'Lateral step-up exercise'),
('Side straddle hops', 'plyometric', true, 'Lateral straddle jumping'),
('Side to Side Arm Swings', 'warm_up', true, 'Lateral arm swinging'),
('Single Leg Bounds', 'plyometric', true, 'Single leg bounding'),
('Single Leg Curls', 'strength', true, 'Single leg hamstring curl'),
('Single Leg Hamstring (stretch)', 'flexibility', true, 'Single leg hamstring stretch'),
('Single Leg Hops (SL HOPS)', 'plyometric', true, 'Single leg hopping'),
('Single Leg Skipovers', 'plyometric', true, 'Single leg skip over'),
('Single Leg Squats', 'strength', true, 'Single leg squat'),
('Single Leg Static/Dynamic Skipovers', 'plyometric', true, 'Single leg skip variations'),
('Single Leg Tuck Jumps (SL Tuck Jumps)', 'plyometric', true, 'Single leg tuck jumps'),
('Single leg wall sit', 'strength', true, 'Single leg wall sit'),
('Sit ups tossing', 'strength', true, 'Sit-ups with ball toss'),
('Ski jumps', 'plyometric', true, 'Lateral ski jumping'),
('Skip Lunges (Forward, Backward)', 'plyometric', true, 'Skipping lunge variations'),
('Skipovers Left Lead Leg', 'plyometric', true, 'Left leg skip over'),
('Skipovers Right Lead Leg', 'plyometric', true, 'Right leg skip over'),
('Skips for distance', 'drill', true, 'Distance skipping'),
('Skips for height', 'drill', true, 'Height skipping'),
('SL Butt Kicks', 'drill', true, 'Single leg butt kicks'),
('SL Cycle Hops', 'plyometric', true, 'Single leg cycling hops'),
('SL Lateral Hops', 'plyometric', true, 'Single leg lateral hops'),
('SL Pogo Jumps', 'plyometric', true, 'Single leg pogo jumps'),
('Sled push', 'strength', true, 'Sled pushing exercise'),
('Sleds (forward, backward, sideways)', 'strength', true, 'Various sled exercises'),
('Snatch (Dumbbell, Barbell, floor, knee, thigh)', 'strength', true, 'Olympic snatch variations'),
('Snatch Pulls', 'strength', true, 'Snatch pulling phase'),
('Spanish squat', 'strength', true, 'Squat variation'),
('Speed Bounds', 'plyometric', true, 'Fast bounding exercise'),
('Speed Skaters', 'plyometric', true, 'Lateral skating movement'),
('Spinal Roll', 'flexibility', true, 'Spinal mobility exercise'),
('Split Jumps', 'plyometric', true, 'Split position jumps'),
('Split Snatch', 'strength', true, 'Split position snatch'),
('Split Stretch', 'flexibility', true, 'Split position stretching'),
('Sprint (Maximums, Full Approaches, etc.)', 'running', true, 'Maximum speed running'),
('Squat Chest (throw)', 'plyometric', true, 'Squat with chest throw'),
('Squat Jumps', 'plyometric', true, 'Explosive squat jumps'),
('Squat pulses', 'strength', true, 'Pulsing squat exercise'),
('Squat Toe Raises', 'strength', true, 'Squat with calf raise'),
('Squats', 'strength', true, 'Basic squat exercise'),
('Stadium Circuit / Stadium Stairs (Singles, Doubles etc.)', 'running', true, 'Stadium stair exercises'),
('Standing Accelerations (2 pt., 3 pt.)', 'drill', true, 'Standing start accelerations'),
('Standing Ankle Dorsi-Flexion', 'strength', true, 'Ankle dorsiflexion exercise'),
('Standing Calf R/L (stretch)', 'flexibility', true, 'Standing calf stretch'),
('Standing Good Mornings', 'strength', true, 'Standing hip hinge'),
('Standing LJ / Broad Jump', 'plyometric', true, 'Standing long jump'),
('Standing Overhead Forward (throw)', 'plyometric', true, 'Standing overhead throw'),
('Standing Triple Jump', 'plyometric', true, 'Standing triple jump'),
('Star Jumps', 'plyometric', true, 'Star position jumps'),
('Stationary High knees', 'drill', true, 'Stationary high knee drill'),
('Steering Drill', 'drill', true, 'Direction change drill'),
('Step Over the Opposite Knee (part of Frontside Mechanics cue)', 'drill', true, 'Running form cue'),
('Step ups', 'strength', true, 'Step-up exercise'),
('Straddle jumps', 'plyometric', true, 'Straddle position jumps'),
('Straddle Stretch Middle/Right/Left', 'flexibility', true, 'Straddle stretching positions'),
('Straight Leg Bounds', 'plyometric', true, 'Straight leg bounding'),
('Straight Leg Deadlifts', 'strength', true, 'Straight leg deadlift'),
('Straight Leg Shuffle', 'drill', true, 'Straight leg shuffling'),
('Stride', 'running', true, 'Striding exercise'),
('Suitcase Carry', 'strength', true, 'Unilateral carry exercise'),
('Suitcase crunches', 'strength', true, 'Suitcase position crunches'),
('Sumo Squats', 'strength', true, 'Wide stance squat'),
('Superman', 'strength', true, 'Back extension exercise'),
('Superman w/ Twist', 'strength', true, 'Back extension with rotation'),
('Swing Arms from the Shoulders (part of Frontside Mechanics cue)', 'drill', true, 'Running form cue'),

-- T-W exercises
('TJ 6 step Hop and Step', 'drill', true, 'Triple jump drill'),
('TIB Raises / Tib raise', 'strength', true, 'Tibialis anterior strengthening'),
('Tight High Knee''s Rotary', 'drill', true, 'Tight high knee drill'),
('Toe Touches', 'flexibility', true, 'Forward bending stretch'),
('Toe-Up (part of Frontside Mechanics cue)', 'drill', true, 'Running form cue'),
('Trail Leg Circles', 'drill', true, 'Hurdle trail leg drill'),
('Tuck Jumps', 'plyometric', true, 'Knee tuck jumps'),
('Turnarounds', 'drill', true, 'Direction change drill'),
('Twist Lunges', 'strength', true, 'Rotational lunge exercise'),
('Underhand tosses (Medicine Ball)', 'plyometric', true, 'Underhand medicine ball throw'),
('Up down planks', 'strength', true, 'Plank up-down exercise'),
('V Ups / v-ups', 'strength', true, 'V-position sit-ups'),
('V-sit pass the ball', 'strength', true, 'V-sit with ball passing'),
('Vertical Jump', 'plyometric', true, 'Maximum vertical jump'),
('Walk on heels', 'drill', true, 'Heel walking drill'),
('Walk on inside/outside of foot (forward/backward)', 'drill', true, 'Foot position walking'),
('Walk on toes', 'drill', true, 'Toe walking drill'),
('Walkovers Left/Right Lead Leg', 'flexibility', true, 'Dynamic leg walkovers'),
('Walking Inch Worm (see Inch Worms)', 'strength', true, 'Walking plank exercise'),
('Walking Knee to Chest', 'flexibility', true, 'Walking knee hugs'),
('Walking Overhead Med Hurdles', 'plyometric', true, 'Walking with overhead ball'),
('Walking opposite elbow to knee', 'flexibility', true, 'Cross-body walking stretch'),
('Walking opposite elbow to knee with lunge', 'flexibility', true, 'Cross-body lunge stretch'),
('Walking on heels (sprinting arms)', 'drill', true, 'Heel walk with arm action'),
('Walking on toes (sprinting arms)', 'drill', true, 'Toe walk with arm action'),
('Walking quad stretch', 'flexibility', true, 'Walking quadriceps stretch'),
('Walking stretches - quads, hams, glutes', 'flexibility', true, 'Walking stretch series'),
('Walking Lunges', 'strength', true, 'Walking lunge exercise'),
('Wall drill calf raises', 'strength', true, 'Wall-supported calf raises'),
('Wall toss', 'plyometric', true, 'Wall ball exercise'),
('Water Break / Electrolyte Break (activity, not exercise)', 'rest_interval', true, 'Hydration break'),
('Weave (running drill)', 'drill', true, 'Weaving running drill'),
('Wharton rope stretches', 'flexibility', true, 'Rope-assisted stretching'),
('Wicket Speed Dev (likely a drill series)', 'drill', true, 'Wicket speed development'),
('Wideouts', 'drill', true, 'Wide step drill'),
('Windmill', 'flexibility', true, 'Windmill stretching exercise'),
('Ws (drill)', 'drill', true, 'W-position drill')

ON CONFLICT (name) DO NOTHING;